### PR TITLE
Add word_separators note to readme

### PR DESCRIPTION
**Pull request by chere005**

### CODE REVIEW

**Comment by Shigma** [comment]
Actually, a sublime package is allowed to have a settings file in it. So why not add such a file?

**Comment by chere005** [comment]
Is naming the file WolframLanguage.sublime-settings and adding it to the root of this repo sufficient so that the setting only takes place when using WL highlighting?

**Comment by ViktorQvarfordt** [comment]
As far as I remember, yes. Have a look at my syntax package for Julia, which previously used a settings file: https://github.com/JuliaEditorSupport/Julia-sublime/commit/38ae482c7930845c25a6bfcbb48bc338e156b5f9

**Comment by Shigma** [comment]
@chere005 Well as far as I concerned, some settings take effects only in the language of the package it belongs to, but others may take effects under all the circumstances. It may be necessary to have a test.

**Comment by batracos** [comment]
I keep a `WolframLanguage.sublime-settings` in the paclet root with
```
{
	"extensions":
	[
		"m",
		"wl",
		"wls",
		"nb"
	],
	"word_separators": "./\\()\"'-:,.;<>~!@#%^&*|+=[]{}`~?_"
}
```
According to @chere005 we should add a couple more for the test files.

**Pull request closed without merging**
