### PR TITLE
Fix problems 3, 4 and 5 in #7 

### PR DESCRIPTION
**Pull request by Shigma**

### CODE REVIEW

**Comment by ViktorQvarfordt** [comment]
Awesome! Are you sure we don't want to keep the build files, for future reference and in case of future changes to the wolfram language?

**Comment by Shigma** [comment]
@ViktorQvarfordt Sorry, I almost forgot these sort of things.
Well, keeping these build files is a good idea, but at least not for master branch. Maybe start a new develop branch with the `build` directory and leaving master branch clean is another choice. What do you think?
:relaxed:

**Comment by ViktorQvarfordt** [comment]
I have no issue with a `build` folder checked in to the master branch. Multiple branches might just get annoying. However, the master branch is what is being pulled in to Sublime, and it is quite wasteful to ship the build files, so I think that a dev-branch sounds good. I'm not sure if one can add new branches in a PR so I added you as a collaborator to the project.

**Comment by chere005** [comment]
This breaks comment matching on some code that looks like this for me:

```
(*(*	Comment *)
2+2
]*)
```

**Comment by Shigma** [comment]
@chere005 Thank you for your advise.
The problem about the comment will be fixed as soon as possible.
About your later comment, do you mean `bar_String` should be treated as a whole?

**Comment by Shigma** [comment]
@ViktorQvarfordt Thank a lot, but ...... are you sure you added me as a collaborator? It seems to me that the access to writing hasn't changed. 😞

**Comment by ViktorQvarfordt** [comment]
You can see the invite here:
https://github.com/ViktorQvarfordt/Sublime-WolframLanguage/invitations :)

**Comment by Shigma** [comment]
@chere005 Thanks for your reminding me of the problems this pr already has. But the merging is only for setting the build directory.
The problem you mentioned has been fixed in my recent commit in branch develop. If there is any further question, just tell me.

**Pull request merged**
